name: v_platform
description: VPlatformFile is a Dart package that provides easy handling of files from paths, URLs, assets, and bytes, with utilities for metadata, MIME type, and serialization support.
version: 2.1.3
homepage: https://github.com/v-chat-sdk/v_platform

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mime_type: ^1.0.1
  mime: ^2.0.0
  path: ^1.9.0
  universal_html: ^2.2.4
  file_sizes: ^1.0.6
  http_parser: ^4.0.2
  http: ^1.2.2
dev_dependencies:
  flutter_lints: ^5.0.0

flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux: